services:
  backend:
    build:
      context: ./backend
    container_name: "orassistant-backend"
    ports:
      - "8000:8000"
    # healthcheck:
    #   test: "curl -f http://localhost:8000/healthcheck || exit 1"
    #   interval: 30s
    #   timeout: 10s
    #   retries: 5
    #   start_period: 30 s # todo: make sure that this healthcheck starts after the API in the backend is ready.
  
  frontend:
    build:
      context: ./frontend
    container_name: "orassistant-frontend"
    ports:
      - "8501:8501"
    environment:
      - CHAT_ENDPOINT=http://backend:8000

  # health-checker:
  #   build: ./common
  #   container_name: "orassistant-health-checker"
  #   depends_on:
  #     backend:
  #       condition: service_healthy
  #   healthcheck:
  #     test: "ls /app || exit 1"
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3
  #     start_period: 5s
