name: Build Backend Docker Image 

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Initialize .env
      run: |
        cp backend/.env.example backend/.env
        sed -i s/{{GOOGLE_API_KEY}}/${{ secrets.GOOGLE_API_KEY }} backend/.env
        cat backend/.env
      
    - name: Build image
      uses: docker/build-push-action@v2
      with:
        context: backend
        file: backend/Dockerfile
        push: false
        tags: ${{ secrets.DOCKERHUB_USERNAME }}

    # TODO: Deploy action on self-hosted?
