name: Update Changelog

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  updateChangeLog:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Create Changelog file
        run: |
          make changelog

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GH_PAT }}
          commit-message: Update report
          committer: Jack Luar <jluar@precisioninno.com>
          author: Jack Luar <jluar@precisioninno.com>
          signoff: true
          base: master
          branch: update-chglog
          delete-branch: true
          title: Changelog Update
          body: |
            - Auto-generated by [create-pull-request][1]
            [1]: https://github.com/peter-evans/create-pull-request
          labels: |
            docs
          assignees: luarss
